name: QFlasher
options:
  bundleIdPrefix: com.johanlundgren
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: QFlasher
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  QFlasher:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/AppIcon.icns
      - path: Resources/AppIcon.png
      - path: Resources/flash-uno-q.png
      - path: Resources/arduino-flasher-cli
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/QFlasher.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.johanlundgren.qflasher
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
    preBuildScripts:
      - name: "Set CLI Permissions"
        script: |
          chmod +x "${SRCROOT}/Resources/arduino-flasher-cli" 2>/dev/null || true
        basedOnDependencyAnalysis: false
